# Generated by Django 4.0.4 on 2022-04-30 17:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motifs', '0001_initial'),
        ('projets', '0002_remove_projets_motifs_remove_projets_observation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debloquer_Par',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saisie_par', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lever', models.CharField(choices=[('levés', 'leves'), ('Non levés', 'non_leves')], max_length=100)),
                ('detail_obs', models.CharField(max_length=255, null=True)),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motifs.motifs')),
                ('projets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.projets')),
            ],
            options={
                'db_table': 'debloquer_par',
            },
        ),
    ]
