# Generated by Django 4.0.4 on 2022-04-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debloqueur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debloqueur',
            name='dtdebloqueur',
        ),
    ]
