# Generated by Django 4.0.4 on 2022-04-20 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debloqueur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debloqueur',
            name='date_deblocage',
            field=models.DateTimeField(blank=True, default=datetime.date, null=True),
        ),
    ]
