# Generated by Django 4.0.4 on 2022-04-25 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('debloqueur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debloqueur',
            name='debloqueur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debloqueur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='debloqueur',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debloqueur',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='debloqueur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='debloqueur',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='debloqueur',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='debloqueur',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='debloqueur',
            table=None,
        ),
    ]
