# Generated by Django 4.0.4 on 2022-04-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debloqueur', '0002_debloqueur_debloqueur_debloqueur_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debloqueur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='debloqueur',
            name='prenom',
        ),
        migrations.AddField(
            model_name='debloqueur',
            name='first_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debloqueur',
            name='last_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
