# Generated by Django 4.0.4 on 2022-04-26 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debloqueur', '0003_remove_debloqueur_nom_remove_debloqueur_prenom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debloqueur',
            old_name='username',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='debloqueur',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='debloqueur',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='debloqueur',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='debloqueur',
            name='jwt_secret',
        ),
        migrations.RemoveField(
            model_name='debloqueur',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='debloqueur',
            name='last_name',
        ),
        migrations.AddField(
            model_name='debloqueur',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debloqueur',
            name='prenom',
            field=models.CharField(default='default', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debloqueur',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='debloqueur',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='debloqueur',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AlterModelTable(
            name='debloqueur',
            table='debloqueur',
        ),
    ]
