# Generated by Django 4.0.4 on 2022-04-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debloqueur', '0010_alter_debloqueur_date_deblocage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debloqueur',
            old_name='date_deblocage',
            new_name='date_debloque',
        ),
    ]
