# Generated by Django 4.0.4 on 2022-04-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debloqueur', '0011_rename_date_deblocage_debloqueur_date_debloque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debloqueur',
            old_name='date_debloque',
            new_name='date_debloqueur',
        ),
    ]
