# Generated by Django 4.0.4 on 2022-04-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debloqueur', '0012_rename_date_debloque_debloqueur_date_debloqueur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debloqueur',
            name='date_debloqueur',
        ),
        migrations.AddField(
            model_name='debloqueur',
            name='date_debloque',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
