# Generated by Django 4.0.4 on 2022-04-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debloqueur', '0013_remove_debloqueur_date_debloqueur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debloqueur',
            name='date_debloque',
        ),
        migrations.AddField(
            model_name='debloqueur',
            name='date_debloqueur',
            field=models.DateTimeField(default='default'),
            preserve_default=False,
        ),
    ]
