# Generated by Django 4.0.4 on 2022-04-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debloqueur', '0014_remove_debloqueur_date_debloque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debloqueur',
            name='date_debloqueur',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
