# Generated by Django 4.0.4 on 2022-04-20 11:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secteurs', models.CharField(max_length=255, unique=True)),
                ('branche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branche.branche')),
            ],
            options={
                'db_table': 'Activite',
            },
        ),
    ]
