# Generated by Django 4.0.4 on 2022-04-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activite',
            table='activite',
        ),
    ]
