# Generated by Django 4.0.4 on 2022-04-24 10:13

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('prenom', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(null=True)),
                ('nationalite', models.CharField(max_length=100)),
                ('gerant', models.BooleanField()),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinValueValidator(8)])),
            ],
            options={
                'db_table': 'gerant',
            },
        ),
    ]
