# Generated by Django 4.0.4 on 2022-04-25 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerant',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Veuillez introduire votre numéro de téléphone sous  format: '+999999999'. en 15 carataires.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
