# Generated by Django 4.0.4 on 2022-04-20 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerant', '0001_initial'),
        ('commune', '0001_initial'),
        ('activite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raison_social', models.CharField(max_length=255, unique=True)),
                ('nb_employe_prevus', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('nb_employe_reel', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('type_entrp', models.CharField(max_length=100)),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commune.commune')),
                ('gerant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerant.gerant')),
                ('secteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activite.activite')),
            ],
            options={
                'db_table': 'entreprise',
            },
        ),
    ]
