# Generated by Django 4.0.4 on 2022-04-24 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motifs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_contrainte', models.CharField(max_length=255, unique=True)),
                ('detail', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'motifs',
            },
        ),
    ]
