# Generated by Django 4.0.4 on 2022-04-20 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wilaya', models.CharField(max_length=255, unique=True)),
                ('code_wilaya', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'wilaya',
            },
        ),
    ]
