# Generated by Django 4.0.4 on 2022-04-30 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projets',
            name='motifs',
        ),
        migrations.RemoveField(
            model_name='projets',
            name='observation',
        ),
        migrations.AddField(
            model_name='projets',
            name='statue_projets',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projets',
            name='code_fichier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projets',
            name='etat_projet',
            field=models.CharField(choices=[('EN_EXPLOITATION', 'EN_EXPLOITATION'), ('NON_MIS_EN_EXPLOITATION', 'NON_MIS_EN_EXPLOITATION')], max_length=100),
        ),
        migrations.AlterField(
            model_name='projets',
            name='nb_employe_prevus',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='projets',
            name='nb_employe_reel',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='projets',
            name='projet',
            field=models.CharField(max_length=255),
        ),
    ]
