# Generated by Django 4.0.4 on 2022-04-21 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deblocages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt_dablocage', models.DateField()),
            ],
            options={
                'db_table': 'deblocages',
            },
        ),
    ]
