# Generated by Django 4.0.4 on 2022-04-20 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wilaya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commune', models.CharField(max_length=255, unique=True)),
                ('code_postal', models.CharField(max_length=255, unique=True)),
                ('wilaya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilaya.wilaya')),
            ],
            options={
                'db_table': 'commune',
            },
        ),
    ]
