# Generated by Django 4.0.4 on 2022-04-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='code_postal',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
