# Generated by Django 4.0.4 on 2022-04-21 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deblocages', '0001_initial'),
        ('motifs', '0001_initial'),
        ('debloqueur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deblocages',
            name='deblocage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debloqueur.debloqueur'),
        ),
        migrations.AddField(
            model_name='deblocages',
            name='motif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motifs.motifs'),
        ),
    ]
